[package]
name = "silly"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite = "0.21.0"

[dependencies.dsp]
path = '../dsp'

[dependencies.volk-rs]
git = 'https://github.com/theverygaming/volk-rs.git'
